### ISSUE TITLE
Endpoint not working

### ISSUE THREAD

**Issue by anju-infracloud** [ashutiwari/urlshortner#1]
I ran following command, but seeing 400 error

$ curl -X POST http://localhost:8085/crete_short_url -d '{"url": "facebook.com"}' -H "Content-Type: application/json"
{"timestamp":"2021-04-05T06:58:54.491+00:00","status":400,"error":"Bad Request","message":"","path":"/crete_short_url"}

API endpoint is as per the swagger mentioned in https://github.com/ashutiwari/urlshortner/blob/develop/README.md

**Comment by ashutiwari** [comment]
@anju-infracloud 
Hi Anju,
It is expected response.
I have added a url validator in api ,
facebook.com is not a valid url , can you please try with **https://www.facebook.com** and let me know if it will work.
Thanks.
